// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

using System.Collections.Generic;

namespace behaviac
{
	partial class AgentMeta
	{
		private class CMethod_behaviac_Agent_VectorAdd : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorAdd()
			{
			}

			public CMethod_behaviac_Agent_VectorAdd(CMethod_behaviac_Agent_VectorAdd rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorAdd(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<System.Collections.IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorAdd((System.Collections.IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorClear : CAgentMethodVoidBase
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorClear()
			{
			}

			public CMethod_behaviac_Agent_VectorClear(CMethod_behaviac_Agent_VectorClear rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorClear(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<System.Collections.IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				behaviac.Agent.VectorClear((System.Collections.IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorContains : CAgentMethodBase<bool>
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorContains()
			{
			}

			public CMethod_behaviac_Agent_VectorContains(CMethod_behaviac_Agent_VectorContains rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorContains(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<System.Collections.IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				_returnValue.value = behaviac.Agent.VectorContains((System.Collections.IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorLength : CAgentMethodBase<int>
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorLength()
			{
			}

			public CMethod_behaviac_Agent_VectorLength(CMethod_behaviac_Agent_VectorLength rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorLength(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<System.Collections.IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_returnValue.value = behaviac.Agent.VectorLength((System.Collections.IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorRemove : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorRemove()
			{
			}

			public CMethod_behaviac_Agent_VectorRemove(CMethod_behaviac_Agent_VectorRemove rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorRemove(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<System.Collections.IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorRemove((System.Collections.IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}


		static partial void registerMeta()
		{
			// ---------------------------------------------------------------------
			// properties
			// ---------------------------------------------------------------------

			AgentMeta meta;

			// behaviac.Agent
			meta = new AgentMeta();
			_agentMetas[2436498804] = meta;
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { behaviac.Agent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// behaviac.BaseAgent
			meta = new AgentMeta();
			_agentMetas[1443334615] = meta;
			meta.RegisterMemberProperty(4038800660, new CMemberProperty<LuaInterface.LuaFunction>("fun", delegate(Agent self, LuaInterface.LuaFunction value) { ((behaviac.BaseAgent)self).fun = value; }, delegate(Agent self) { return ((behaviac.BaseAgent)self).fun; }));
			meta.RegisterMemberProperty(3269339607, new CMemberProperty<LuaInterface.LuaTable>("table", delegate(Agent self, LuaInterface.LuaTable value) { ((behaviac.BaseAgent)self).table = value; }, delegate(Agent self) { return ((behaviac.BaseAgent)self).table; }));
			meta.RegisterMethod(358986303, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((behaviac.BaseAgent)self).Action(param0); }));
			meta.RegisterMethod(1144956132, new CAgentMethod<string, string>(delegate(Agent self, string param0) { return ((behaviac.BaseAgent)self).Get(param0); }));
			meta.RegisterMethod(2605016108, new CAgentMethodVoid<string, string>(delegate(Agent self, string param0, string param1) { ((behaviac.BaseAgent)self).Set(param0, param1); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { behaviac.BaseAgent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// td_buffagent
			meta = new AgentMeta();
			_agentMetas[1073624494] = meta;
			meta.RegisterMemberProperty(4272831949, new CMemberProperty<int>("count", delegate(Agent self, int value) { ((td_buffagent)self).count = value; }, delegate(Agent self) { return ((td_buffagent)self).count; }));
			meta.RegisterMemberProperty(2101220778, new CMemberProperty<bool>("init", delegate(Agent self, bool value) { ((td_buffagent)self).init = value; }, delegate(Agent self) { return ((td_buffagent)self).init; }));
			meta.RegisterMemberProperty(3710006845, new CMemberProperty<int>("curdotimes", delegate(Agent self, int value) { ((td_buffagent)self).curdotimes = value; }, delegate(Agent self) { return ((td_buffagent)self).curdotimes; }));
			meta.RegisterMemberProperty(1013560976, new CMemberProperty<float>("intervaltime", delegate(Agent self, float value) { ((td_buffagent)self).intervaltime = value; }, delegate(Agent self) { return ((td_buffagent)self).intervaltime; }));
			meta.RegisterMemberProperty(3965406110, new CMemberProperty<float>("curlife", delegate(Agent self, float value) { ((td_buffagent)self).curlife = value; }, delegate(Agent self) { return ((td_buffagent)self).curlife; }));
			meta.RegisterMemberProperty(2855629235, new CMemberProperty<int>("dotimes", delegate(Agent self, int value) { ((td_buffagent)self).dotimes = value; }, delegate(Agent self) { return ((td_buffagent)self).dotimes; }));
			meta.RegisterMemberProperty(1888273998, new CMemberProperty<float>("life", delegate(Agent self, float value) { ((td_buffagent)self).life = value; }, delegate(Agent self) { return ((td_buffagent)self).life; }));
			meta.RegisterMethod(1451222367, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_buffagent)self).addskillobj(param0); }));
			meta.RegisterMethod(842115270, new CAgentMethod<bool, string>(delegate(Agent self, string param0) { return ((td_buffagent)self).random(param0); }));
			meta.RegisterMethod(1237974238, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_buffagent)self).removeattribute(); }));
			meta.RegisterMethod(1790837007, new CAgentMethod<bool>(delegate(Agent self) { return ((td_buffagent)self).istargetdie(); }));
			meta.RegisterMethod(1457829689, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_buffagent)self).subtractround(); }));
			meta.RegisterMethod(1006176502, new CAgentMethod<bool>(delegate(Agent self) { return ((td_buffagent)self).cangobuffeffect(); }));
			meta.RegisterMethod(881475482, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_buffagent)self).addbuff(param0); }));
			meta.RegisterMethod(4010014689, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_buffagent)self).addshield(param0); }));
			meta.RegisterMethod(315227608, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_buffagent)self).addeffect(param0); }));
			meta.RegisterMethod(118452716, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_buffagent)self).addstun(); }));
			meta.RegisterMethod(3596137716, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_buffagent)self).destroyself(); }));
			meta.RegisterMethod(98167646, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_buffagent)self).adddamage(param0); }));
			meta.RegisterMethod(1014209351, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_buffagent)self).addatrribute(param0); }));
			meta.RegisterMethod(4039010040, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_buffagent)self).addtimes(); }));
			meta.RegisterMethod(2149167149, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_buffagent)self).doskill(param0); }));
			meta.RegisterMethod(1084385188, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_buffagent)self).movetotheother(param0); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { td_buffagent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// td_bulletagent
			meta = new AgentMeta();
			_agentMetas[2950391394] = meta;
			meta.RegisterMemberProperty(1954023585, new CMemberProperty<int>("explodetimes", delegate(Agent self, int value) { ((td_bulletagent)self).explodetimes = value; }, delegate(Agent self) { return ((td_bulletagent)self).explodetimes; }));
			meta.RegisterMemberProperty(2101220778, new CMemberProperty<int>("init", delegate(Agent self, int value) { ((td_bulletagent)self).init = value; }, delegate(Agent self) { return ((td_bulletagent)self).init; }));
			meta.RegisterMemberProperty(3229119586, new CMemberProperty<float>("lifetime", delegate(Agent self, float value) { ((td_bulletagent)self).lifetime = value; }, delegate(Agent self) { return ((td_bulletagent)self).lifetime; }));
			meta.RegisterMemberProperty(948253088, new CMemberProperty<string>("hangpoint", delegate(Agent self, string value) { ((td_bulletagent)self).hangpoint = value; }, delegate(Agent self) { return ((td_bulletagent)self).hangpoint; }));
			meta.RegisterMemberProperty(155620650, new CMemberProperty<float>("speed", delegate(Agent self, float value) { ((td_bulletagent)self).speed = value; }, delegate(Agent self) { return ((td_bulletagent)self).speed; }));
			meta.RegisterMethod(1731056598, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_bulletagent)self).addnormalexplode(param0); }));
			meta.RegisterMethod(98167646, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_bulletagent)self).adddamage(param0); }));
			meta.RegisterMethod(1451222367, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_bulletagent)self).addskillobj(param0); }));
			meta.RegisterMethod(3662752869, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_bulletagent)self).normalrun(); }));
			meta.RegisterMethod(842115270, new CAgentMethod<bool, string>(delegate(Agent self, string param0) { return ((td_bulletagent)self).random(param0); }));
			meta.RegisterMethod(2050724149, new CAgentMethod<bool>(delegate(Agent self) { return ((td_bulletagent)self).touchtarget(); }));
			meta.RegisterMethod(1790837007, new CAgentMethod<bool>(delegate(Agent self) { return ((td_bulletagent)self).istargetdie(); }));
			meta.RegisterMethod(754350556, new CAgentMethodVoid(delegate(Agent self) { ((td_bulletagent)self).setautotarget(); }));
			meta.RegisterMethod(3209384603, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_bulletagent)self).setnearesttarget(param0); }));
			meta.RegisterMethod(881475482, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_bulletagent)self).addbuff(param0); }));
			meta.RegisterMethod(3596137716, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_bulletagent)self).destroyself(); }));
			meta.RegisterMethod(897419734, new CAgentMethod<bool>(delegate(Agent self) { return ((td_bulletagent)self).hastarget(); }));
			meta.RegisterMethod(3299108968, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_bulletagent)self).addexplodetimes(); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { td_bulletagent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// td_skillagent
			meta = new AgentMeta();
			_agentMetas[3147757258] = meta;
			meta.RegisterMemberProperty(1577915041, new CMemberProperty<int>("curwaitframe", delegate(Agent self, int value) { ((td_skillagent)self).curwaitframe = value; }, delegate(Agent self) { return ((td_skillagent)self).curwaitframe; }));
			meta.RegisterMemberProperty(2089589801, new CMemberProperty<int>("targetnum", delegate(Agent self, int value) { ((td_skillagent)self).targetnum = value; }, delegate(Agent self) { return ((td_skillagent)self).targetnum; }));
			meta.RegisterMemberProperty(1039663545, new CMemberProperty<int>("curloopcount", delegate(Agent self, int value) { ((td_skillagent)self).curloopcount = value; }, delegate(Agent self) { return ((td_skillagent)self).curloopcount; }));
			meta.RegisterMemberProperty(1803846635, new CMemberProperty<bool>("done", delegate(Agent self, bool value) { ((td_skillagent)self).done = value; }, delegate(Agent self) { return ((td_skillagent)self).done; }));
			meta.RegisterMethod(3736267469, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).gettargetbydis(param0); }));
			meta.RegisterMethod(3653177550, new CAgentMethod<behaviac.EBTStatus, float>(delegate(Agent self, float param0) { return ((td_skillagent)self).changemodelscale(param0); }));
			meta.RegisterMethod(1451222367, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).addskillobj(param0); }));
			meta.RegisterMethod(3341587439, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).createbullet(param0); }));
			meta.RegisterMethod(4203555871, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_skillagent)self).wait(); }));
			meta.RegisterMethod(628000258, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).adddamagetotarget(param0); }));
			meta.RegisterMethod(842115270, new CAgentMethod<bool, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).random(param0); }));
			meta.RegisterMethod(871647092, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_skillagent)self).getcharactertarget(); }));
			meta.RegisterMethod(448705070, new CAgentMethod<int>(delegate(Agent self) { return ((td_skillagent)self).getpower(); }));
			meta.RegisterMethod(1994171705, new CAgentMethod<int, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).getcharactercountbybaseid(param0); }));
			meta.RegisterMethod(167787209, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).getdowntargetlstbyattr(param0); }));
			meta.RegisterMethod(283996399, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).getuptargetlstbyattr(param0); }));
			meta.RegisterMethod(366731648, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).gettargetbycharacterbaseid(param0); }));
			meta.RegisterMethod(727688788, new CAgentMethod<int, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).getcharactercountbytype(param0); }));
			meta.RegisterMethod(3268433908, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).addpower(param0); }));
			meta.RegisterMethod(2875629888, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_skillagent)self).getselftotarget(); }));
			meta.RegisterMethod(1676202411, new CAgentMethod<bool>(delegate(Agent self) { return ((td_skillagent)self).istargetplayeralldie(); }));
			meta.RegisterMethod(3051832754, new CAgentMethod<bool>(delegate(Agent self) { return ((td_skillagent)self).istargetplayerdie(); }));
			meta.RegisterMethod(2138732490, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_skillagent)self).cleartarget(); }));
			meta.RegisterMethod(1696787106, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).addeffecttotarget(param0); }));
			meta.RegisterMethod(881475482, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).addbuff(param0); }));
			meta.RegisterMethod(2121051778, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).addeffecttoself(param0); }));
			meta.RegisterMethod(3110295921, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).getskilltargetbytargetcircle(param0); }));
			meta.RegisterMethod(2117650844, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).getskilltargetlst(param0); }));
			meta.RegisterMethod(430248983, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).getskilltargetbysquare(param0); }));
			meta.RegisterMethod(451754120, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).getskilltargetbyskillposcircle(param0); }));
			meta.RegisterMethod(2674889422, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).getskilltargetbycircle(param0); }));
			meta.RegisterMethod(2711014069, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).findrandomtarget(param0); }));
			meta.RegisterMethod(2061509198, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).addeffecttoskillpos(param0); }));
			meta.RegisterMethod(2123664823, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_skillagent)self).goafterskill(); }));
			meta.RegisterMethod(1191828068, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((td_skillagent)self).gopreskill(); }));
			meta.RegisterMethod(1569252558, new CAgentMethod<behaviac.EBTStatus, string>(delegate(Agent self, string param0) { return ((td_skillagent)self).putactioninfo(param0); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { td_skillagent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			AgentMeta.Register<behaviac.EBTStatus>("behaviac.EBTStatus");
			AgentMeta.Register<System.Object>("System.Object");
			AgentMeta.Register<LuaInterface.LuaTable>("LuaInterface.LuaTable");
			AgentMeta.Register<LuaInterface.LuaFunction>("LuaInterface.LuaFunction");
			AgentMeta.Register<behaviac.Agent>("behaviac.Agent");
			AgentMeta.Register<behaviac.BaseAgent>("behaviac.BaseAgent");
			AgentMeta.Register<td_buffagent>("td_buffagent");
			AgentMeta.Register<td_bulletagent>("td_bulletagent");
			AgentMeta.Register<td_skillagent>("td_skillagent");

		}

		static partial void unRegisterMeta()
		{
			AgentMeta.UnRegister<behaviac.EBTStatus>("behaviac.EBTStatus");
			AgentMeta.UnRegister<System.Object>("System.Object");
			AgentMeta.UnRegister<LuaInterface.LuaTable>("LuaInterface.LuaTable");
			AgentMeta.UnRegister<LuaInterface.LuaFunction>("LuaInterface.LuaFunction");
			AgentMeta.UnRegister<behaviac.Agent>("behaviac.Agent");
			AgentMeta.UnRegister<behaviac.BaseAgent>("behaviac.BaseAgent");
			AgentMeta.UnRegister<td_buffagent>("td_buffagent");
			AgentMeta.UnRegister<td_bulletagent>("td_bulletagent");
			AgentMeta.UnRegister<td_skillagent>("td_skillagent");
		}
	}
}
