// ---------------------------------------------------------------------
// This agent file is auto-generated by behaviac designer, but you should
// implement the methods of the agent class if necessary!
// ---------------------------------------------------------------------

using System.Collections.Generic;

namespace behaviac
{
    [behaviac.TypeMetaInfo("BaseAgent", "")]
    public class BaseAgent : behaviac.Agent
    {
        // properties

        [behaviac.MemberMetaInfo("table", "table")]
        public LuaInterface.LuaTable table = null;

        [behaviac.MemberMetaInfo("fun", "fun")]
        public LuaInterface.LuaFunction fun = null;

        // methods

        [behaviac.MethodMetaInfo("Get", "Get")]
        public string Get(string name)
        {
            // Write your logic codes here.

            return table[name].ToString();
        }

        [behaviac.MethodMetaInfo("Set", "Set")]
        public void Set(string name, string value)
        {
            // Write your logic codes here.
            table[name] = value;
        }

        [behaviac.MethodMetaInfo("Action", "Action")]
        public behaviac.EBTStatus Action(string name)
        {
            object[] os = fun.Call(name, table);
            return (EBTStatus)int.Parse(os[0].ToString());
        }

    }
}
