// ---------------------------------------------------------------------
// This agent file is auto-generated by behaviac designer, but you should
// implement the methods of the agent class if necessary!
// ---------------------------------------------------------------------

using System.Collections.Generic;

[behaviac.TypeMetaInfo("td_buffagent", "")]
public class td_buffagent : behaviac.Agent
{
	// properties

	[behaviac.MemberMetaInfo("BUFF_初始化", "init")]
	public bool init = false;

	[behaviac.MemberMetaInfo("BUFF_执行次数", "dotimes")]
	public int dotimes = 0;

	[behaviac.MemberMetaInfo("BUFF_当前执行次数", "curdotimes")]
	public int curdotimes = 0;

	[behaviac.MemberMetaInfo("BUFF_剩余时间", "curlife")]
	public float curlife = 0;

	[behaviac.MemberMetaInfo("BUFF_总时间", "life")]
	public float life = 0;

    [behaviac.MemberMetaInfo("BUFF_层数", "addcount")]
    public int count = 0;

    [behaviac.MemberMetaInfo("BUFF_生效间隔时间", "intervaltime")]
    public float intervaltime = 0;

    // methods

    [behaviac.MethodMetaInfo("BUFF_执行技能", "doskill")]
	public behaviac.EBTStatus doskill(string name)
	{
		// Write your logic codes here.

		return behaviac.EBTStatus.BT_INVALID;
	}

	[behaviac.MethodMetaInfo("BUFF_添加眩晕", "addstun")]
	public behaviac.EBTStatus addstun()
	{
		// Write your logic codes here.

		return behaviac.EBTStatus.BT_INVALID;
	}

	[behaviac.MethodMetaInfo("BUFF_添加护盾", "addshield")]
	public behaviac.EBTStatus addshield(string value)
	{
		// Write your logic codes here.

		return behaviac.EBTStatus.BT_INVALID;
	}

	[behaviac.MethodMetaInfo("BUFF_增加属性（名称#值）", "addatrribute")]
	public behaviac.EBTStatus addatrribute(string info)
	{
		// Write your logic codes here.

		return behaviac.EBTStatus.BT_INVALID;
	}

	[behaviac.MethodMetaInfo("BUFF_还原属性", "removeattribute")]
	public behaviac.EBTStatus removeattribute()
	{
		// Write your logic codes here.

		return behaviac.EBTStatus.BT_INVALID;
	}

	[behaviac.MethodMetaInfo("BUFF_造成伤害", "adddamage")]
	public behaviac.EBTStatus adddamage(string damage)
	{
		// Write your logic codes here.

		return behaviac.EBTStatus.BT_INVALID;
	}

    [behaviac.MethodMetaInfo("BUFF_消亡", "destroyself")]
    public behaviac.EBTStatus destroyself()
    {
        // Write your logic codes here.

        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("BUFF_剩余时间减少", "subtractround")]
    public behaviac.EBTStatus subtractround()
    {
        // Write your logic codes here.

        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("BUFF_执行次数增加", "addtimes")]
    public behaviac.EBTStatus addtimes()
    {
        // Write your logic codes here.

        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("BUFF_概率（0-1）", "random")]
    public bool random(string x)
    {
        // Write your logic codes here.

        return false;
    }

    [behaviac.MethodMetaInfo("BUFF_添加特效（名字#挂点#时间）", "addeffect")]
    public behaviac.EBTStatus addeffect(string info)
    {
        // Write your logic codes here.

        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("BUFF_是否达到生效间隔", "cangobuffeffect")]
    public bool cangobuffeffect()
    {
        // Write your logic codes here.

        return false;
    }

    [behaviac.MethodMetaInfo("BUFF_目标是否死亡", "istargetdie")]
    public bool istargetdie()
    {
        // Write your logic codes here.

        return false;
    }

    [behaviac.MethodMetaInfo("BUFF_转移给离自己最近的目标(目标类型)", "movetotheother")]
    public behaviac.EBTStatus movetotheother(string info)
    {
        // Write your logic codes here.

        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("BUFF_创建技能体(技能id#生效间隔时间#技能体存活时间)", "addskillobj")]
    public behaviac.EBTStatus addskillobj(string info)
    {
        // Write your logic codes here.
        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("BUFF_添加buff", "addbuff")]
    public behaviac.EBTStatus addbuff(string name)
    {
        // Write your logic codes here.

        return behaviac.EBTStatus.BT_INVALID;
    }
}
