// ---------------------------------------------------------------------
// This agent file is auto-generated by behaviac designer, but you should
// implement the methods of the agent class if necessary!
// ---------------------------------------------------------------------

using System.Collections.Generic;

[behaviac.TypeMetaInfo("td_bulletagent", "")]
public class td_bulletagent : behaviac.Agent
{
    // properties
    [behaviac.MemberMetaInfo("子弹_初始化", "init")]
    public int init = 0;

    [behaviac.MemberMetaInfo("子弹_爆炸次数", "explodetimes")]
	public int explodetimes = 0;

	[behaviac.MemberMetaInfo("子弹_速度", "speed")]
	public float speed = 0;

	[behaviac.MemberMetaInfo("子弹_挂点", "hangpoint")]
	public string hangpoint = "";

	[behaviac.MemberMetaInfo("子弹_存活时间", "lifetime")]
	public float lifetime = 0;

	// methods

	[behaviac.MethodMetaInfo("子弹_消亡", "destroyself")]
	public behaviac.EBTStatus destroyself()
	{
		// Write your logic codes here.

		return behaviac.EBTStatus.BT_INVALID;
	}

	[behaviac.MethodMetaInfo("子弹_有目标", "hastarget")]
	public bool hastarget()
	{
		// Write your logic codes here.

		return false;
	}

	[behaviac.MethodMetaInfo("子弹_设置子弹创建者的目标为目标", "setautotarget")]
	public void setautotarget()
	{
		// Write your logic codes here.
	}

	[behaviac.MethodMetaInfo("子弹_飞行", "normalrun")]
	public behaviac.EBTStatus normalrun()
	{
		// Write your logic codes here.

		return behaviac.EBTStatus.BT_INVALID;
	}

	[behaviac.MethodMetaInfo("子弹_接触目标", "touchtarget")]
	public bool touchtarget()
	{
		// Write your logic codes here.

		return false;
	}

    [behaviac.MethodMetaInfo("子弹_创建并显示伤害", "adddamage")]
    public behaviac.EBTStatus adddamage(string damagetype)
    {
        // Write your logic codes here.

        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("子弹_增加爆炸次数", "addexplodetimes")]
    public behaviac.EBTStatus addexplodetimes()
    {
        // Write your logic codes here.

        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("子弹_创建爆炸特效(资源#时间)", "addnormalexplode")]
	public behaviac.EBTStatus addnormalexplode(string info)
	{
		// Write your logic codes here.

		return behaviac.EBTStatus.BT_INVALID;
	}


    [behaviac.MethodMetaInfo("子弹_目标是否死亡", "istargetdie")]
    public bool istargetdie()
    {
        // Write your logic codes here.

        return false;
    }

    [behaviac.MethodMetaInfo("子弹_为目标添加BUFF", "addbuff")]
    public behaviac.EBTStatus addbuff(string name)
    {
        // Write your logic codes here.

        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("子弹_设置最近的敌方单位为目标（弹射范围#是否来回弹）", "setnearesttarget")]
    public behaviac.EBTStatus setnearesttarget(string info)
    {
        // Write your logic codes here.
        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("子弹_创建技能体(技能id#生效间隔时间#技能体存活时间)", "addskillobj")]
    public behaviac.EBTStatus addskillobj(string info)
    {
        // Write your logic codes here.
        return behaviac.EBTStatus.BT_INVALID;
    }

    [behaviac.MethodMetaInfo("子弹_概率（0-1）", "random")]
    public bool random(string x)
    {
        // Write your logic codes here.

        return false;
    }
}
